import { Roboto_Flex } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  variable: "--font-roboto-flex",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoFlex.className}>
        {children}
      </body>
    </html>
  );
}
